In [1]:
import  h5py
import warnings 
warnings.filterwarnings("ignore")

In [2]:
h5=h5py.File("3DIMG_01MAR2022_0000_L2P_IRW.h5")

In [3]:
a=h5.keys()
a

<KeysViewHDF5 ['HEIGHT_ASSIGNMENT_METHOD', 'Latitude', 'Longitude', 'MEAN_BT', 'MIN_BT', 'OBSERVATION_TIME', 'PIXELS', 'PRESSURE', 'QUALITY_INDICATOR', 'SAT_ZEN', 'SCANS', 'UCOMP', 'VCOMP', 'WIND_DIRECTION', 'WIND_SPEED', 'obs', 'time']>

In [5]:
a=[key for key,val in h5.items()]

In [6]:
a

['HEIGHT_ASSIGNMENT_METHOD',
 'Latitude',
 'Longitude',
 'MEAN_BT',
 'MIN_BT',
 'OBSERVATION_TIME',
 'PIXELS',
 'PRESSURE',
 'QUALITY_INDICATOR',
 'SAT_ZEN',
 'SCANS',
 'UCOMP',
 'VCOMP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'obs',
 'time']

In [8]:
import pandas as pd
import numpy as np
data=[]
for i in h5.keys():
    a=h5.get(i)
    arr=np.array(a)
    print(arr)
    data.append(arr)

[0 0 1 ... 1 1 1]
[ 4038  3982  3814 ... -2377 -2443 -3206]
[ 2144  2144  2144 ... 12853 12853 12853]
[245.76 250.94 243.13 ... 295.08 291.33 274.34]
[240.34 244.81 228.64 ... 277.64 266.45 235.87]
[11656800. 11656800. 11656800. ... 11656800. 11656800. 11656800.]
[ 381  401  461 ... 2281 2301 2541]
[600.   600.   433.8  ... 327.81 296.52 393.92]
[0.71 1.   0.56 ... 0.47 0.4  0.62]
[72.37 72.2  71.71 ... 56.56 56.79 59.83]
[  41   41   41 ... 3021 3021 3021]
[12.5  11.88 34.29 ...  9.93 12.32 23.84]
[ 1.3  -0.38  2.11 ... -0.84  1.88  1.68]
[264.08 271.82 266.48 ... 274.84 261.33 265.97]
[24.43 23.1  66.77 ... 19.37 24.23 46.46]
[   0    1    2 ... 6293 6294 6295]
[11656800.]


In [9]:
data

[array([0, 0, 1, ..., 1, 1, 1], dtype=uint16),
 array([ 4038,  3982,  3814, ..., -2377, -2443, -3206], dtype=int16),
 array([ 2144,  2144,  2144, ..., 12853, 12853, 12853], dtype=int16),
 array([245.76, 250.94, 243.13, ..., 295.08, 291.33, 274.34], dtype=float32),
 array([240.34, 244.81, 228.64, ..., 277.64, 266.45, 235.87], dtype=float32),
 array([11656800., 11656800., 11656800., ..., 11656800., 11656800.,
        11656800.]),
 array([ 381,  401,  461, ..., 2281, 2301, 2541]),
 array([600.  , 600.  , 433.8 , ..., 327.81, 296.52, 393.92], dtype=float32),
 array([0.71, 1.  , 0.56, ..., 0.47, 0.4 , 0.62], dtype=float32),
 array([72.37, 72.2 , 71.71, ..., 56.56, 56.79, 59.83], dtype=float32),
 array([  41,   41,   41, ..., 3021, 3021, 3021]),
 array([12.5 , 11.88, 34.29, ...,  9.93, 12.32, 23.84], dtype=float32),
 array([ 1.3 , -0.38,  2.11, ..., -0.84,  1.88,  1.68], dtype=float32),
 array([264.08, 271.82, 266.48, ..., 274.84, 261.33, 265.97], dtype=float32),
 array([24.43, 23.1 , 66.77,

In [10]:
data=pd.DataFrame(data).T
data.columns=h5.keys()

In [11]:
data

HEIGHT_ASSIGNMENT_METHOD  Latitude  Longitude     MEAN_BT      MIN_BT  \
0                          0.0    4038.0     2144.0  245.759995  240.339996   
1                          0.0    3982.0     2144.0  250.940002  244.809998   
2                          1.0    3814.0     2144.0  243.130005  228.639999   
3                          0.0    1927.0     2144.0  276.570007  273.690002   
4                          2.0    1790.0     2144.0  277.100006  273.290009   
...                        ...       ...        ...         ...         ...   
6291                       1.0   -1975.0    12853.0  281.959991  250.139999   
6292                       1.0   -2043.0    12853.0  277.429993  248.119995   
6293                       1.0   -2377.0    12853.0  295.079987  277.640015   
6294                       1.0   -2443.0    12853.0  291.329987  266.450012   
6295                       1.0   -3206.0    12853.0  274.339996  235.869995   

      OBSERVATION_TIME  PIXELS    PRESSURE  QUALITY_INDICATOR    SAT_ZEN  \
0           11656800.0   381.0  600.000000               0.71  72.370003   
1           11656800.0   401.0  600.000000               1.00  72.199997   
2           11656800.0   461.0  433.799988               0.56  71.709999   
3           11656800.0  1061.0  750.000000               0.62  67.339996   
4           11656800.0  1101.0  975.000000               0.59  67.120003   
...                ...     ...         ...                ...        ...   
6291        11656800.0  2161.0  336.309998               0.27  55.240002   
6292        11656800.0  2181.0  338.450012               0.28  55.450001   
6293        11656800.0  2281.0  327.809998               0.47  56.560001   
6294        11656800.0  2301.0  296.519989               0.40  56.790001   
6295        11656800.0  2541.0  393.920013               0.62  59.830002   

       SCANS      UCOMP  VCOMP  WIND_DIRECTION  WIND_SPEED     obs        time  
0       41.0  12.500000   1.30      264.079987   24.430000     0.0  11656800.0  
1       41.0  11.880000  -0.38      271.820007   23.100000     1.0         NaN  
2       41.0  34.290001   2.11      266.480011   66.769997     2.0         NaN  
3       41.0  -2.260000  -3.04       36.700001    7.370000     3.0         NaN  
4       41.0  -5.940000  -0.47       85.480003   11.590000     4.0         NaN  
...      ...        ...    ...             ...         ...     ...         ...  
6291  3021.0   7.160000  -2.13      286.579987   14.520000  6291.0         NaN  
6292  3021.0   9.290000  -2.95      287.619995   18.940001  6292.0         NaN  
6293  3021.0   9.930000  -0.84      274.839996   19.370001  6293.0         NaN  
6294  3021.0  12.320000   1.88      261.329987   24.230000  6294.0         NaN  
6295  3021.0  23.840000   1.68      265.970001   46.459999  6295.0         NaN  

[6296 rows x 17 columns]

In [12]:
data.shape

(6296, 17)

In [13]:
data.isna().sum()

HEIGHT_ASSIGNMENT_METHOD       0
Latitude                       0
Longitude                      0
MEAN_BT                        0
MIN_BT                         0
OBSERVATION_TIME               0
PIXELS                         0
PRESSURE                       0
QUALITY_INDICATOR              0
SAT_ZEN                        0
SCANS                          0
UCOMP                          0
VCOMP                          0
WIND_DIRECTION                 0
WIND_SPEED                     0
obs                            0
time                        6295
dtype: int64

In [15]:
data.describe().T

count          mean          std           min  \
HEIGHT_ASSIGNMENT_METHOD  6296.0  1.269854e+00     0.720131  0.000000e+00   
Latitude                  6296.0 -8.060785e+02  2773.047803 -4.892000e+03   
Longitude                 6296.0  7.665955e+03  2948.477764  2.144000e+03   
MEAN_BT                   6296.0  2.696468e+02    20.487650  1.800900e+02   
MIN_BT                    6296.0  2.543833e+02    26.979385  1.800900e+02   
OBSERVATION_TIME          6296.0  1.165680e+07     0.000000  1.165680e+07   
PIXELS                    6296.0  1.840638e+03   835.110697  4.100000e+01   
PRESSURE                  6296.0  5.813780e+02   277.930277  1.153700e+02   
QUALITY_INDICATOR         6296.0  5.865804e-01     0.221317  1.000000e-02   
SAT_ZEN                   6296.0  4.313635e+01    14.564791  1.450000e+00   
SCANS                     6296.0  1.577680e+03   820.478853  4.100000e+01   
UCOMP                     6296.0  1.772395e+00    12.648668 -2.717000e+01   
VCOMP                     6296.0  6.001827e-01     7.028299 -4.277000e+01   
WIND_DIRECTION            6296.0  1.813139e+02    93.165728  0.000000e+00   
WIND_SPEED                6296.0  2.310702e+01    16.442337  4.290000e+00   
obs                       6296.0  3.147500e+03  1817.642979  0.000000e+00   
time                         1.0  1.165680e+07          NaN  1.165680e+07   

                                   25%           50%           75%  \
HEIGHT_ASSIGNMENT_METHOD  1.000000e+00  1.000000e+00  2.000000e+00   
Latitude                 -3.083000e+03 -1.351000e+03  1.019000e+03   
Longitude                 5.234000e+03  7.750000e+03  1.012200e+04   
MEAN_BT                   2.580100e+02  2.754600e+02  2.856925e+02   
MIN_BT                    2.369300e+02  2.601400e+02  2.778300e+02   
OBSERVATION_TIME          1.165680e+07  1.165680e+07  1.165680e+07   
PIXELS                    1.321000e+03  1.981000e+03  2.501000e+03   
PRESSURE                  3.135875e+02  5.500000e+02  9.000000e+02   
QUALITY_INDICATOR         4.300000e-01  5.900000e-01  7.200000e-01   
SAT_ZEN                   3.364750e+01  4.491000e+01  5.361000e+01   
SCANS                     9.010000e+02  1.601000e+03  2.261000e+03   
UCOMP                    -7.092500e+00 -5.550000e-01  8.185000e+00   
VCOMP                    -2.560000e+00  1.150000e+00  4.722500e+00   
WIND_DIRECTION            1.003700e+02  1.704850e+02  2.683600e+02   
WIND_SPEED                1.232750e+01  1.952000e+01  2.703500e+01   
obs                       1.573750e+03  3.147500e+03  4.721250e+03   
time                      1.165680e+07  1.165680e+07  1.165680e+07   

                                   max  
HEIGHT_ASSIGNMENT_METHOD  2.000000e+00  
Latitude                  4.906000e+03  
Longitude                 1.285300e+04  
MEAN_BT                   3.003000e+02  
MIN_BT                    2.963400e+02  
OBSERVATION_TIME          1.165680e+07  
PIXELS                    3.161000e+03  
PRESSURE                  9.778800e+02  
QUALITY_INDICATOR         1.000000e+00  
SAT_ZEN                   7.491000e+01  
SCANS                     3.021000e+03  
UCOMP                     5.322000e+01  
VCOMP                     3.436000e+01  
WIND_DIRECTION            3.600000e+02  
WIND_SPEED                1.052800e+02  
obs                       6.295000e+03  
time                      1.165680e+07

In [16]:
data.corr()

HEIGHT_ASSIGNMENT_METHOD  Latitude  Longitude  \
HEIGHT_ASSIGNMENT_METHOD                  1.000000 -0.270188   0.034371   
Latitude                                 -0.270188  1.000000  -0.137446   
Longitude                                 0.034371 -0.137446   1.000000   
MEAN_BT                                   0.513374 -0.265095   0.062604   
MIN_BT                                    0.530570 -0.218843   0.002463   
OBSERVATION_TIME                               NaN       NaN        NaN   
PIXELS                                    0.267127 -0.999295   0.139495   
PRESSURE                                  0.675809 -0.150297   0.006814   
QUALITY_INDICATOR                        -0.068615  0.003623   0.133270   
SAT_ZEN                                  -0.126866  0.011717  -0.331891   
SCANS                                     0.034371 -0.137446   1.000000   
UCOMP                                    -0.273327 -0.095483  -0.097118   
VCOMP                                     0.154092  0.040610   0.002575   
WIND_DIRECTION                           -0.195683  0.011323  -0.042810   
WIND_SPEED                               -0.321907 -0.209931   0.076225   
obs                                       0.033194 -0.142117   0.998100   
time                                           NaN       NaN        NaN   

                           MEAN_BT    MIN_BT  OBSERVATION_TIME    PIXELS  \
HEIGHT_ASSIGNMENT_METHOD  0.513374  0.530570               NaN  0.267127   
Latitude                 -0.265095 -0.218843               NaN -0.999295   
Longitude                 0.062604  0.002463               NaN  0.139495   
MEAN_BT                   1.000000  0.864726               NaN  0.261350   
MIN_BT                    0.864726  1.000000               NaN  0.217396   
OBSERVATION_TIME               NaN       NaN               NaN       NaN   
PIXELS                    0.261350  0.217396               NaN  1.000000   
PRESSURE                  0.573172  0.761396               NaN  0.148481   
QUALITY_INDICATOR        -0.027252 -0.002556               NaN -0.001046   
SAT_ZEN                  -0.163073  0.027060               NaN -0.005644   
SCANS                     0.062602  0.002461               NaN  0.139494   
UCOMP                    -0.241266 -0.083077               NaN  0.110345   
VCOMP                     0.136298  0.125771               NaN -0.044587   
WIND_DIRECTION           -0.197666 -0.045183               NaN -0.003280   
WIND_SPEED               -0.302378 -0.241131               NaN  0.225207   
obs                       0.056240 -0.001456               NaN  0.144336   
time                           NaN       NaN               NaN       NaN   

                          PRESSURE  QUALITY_INDICATOR   SAT_ZEN     SCANS  \
HEIGHT_ASSIGNMENT_METHOD  0.675809          -0.068615 -0.126866  0.034371   
Latitude                 -0.150297           0.003623  0.011717 -0.137446   
Longitude                 0.006814           0.133270 -0.331891  1.000000   
MEAN_BT                   0.573172          -0.027252 -0.163073  0.062602   
MIN_BT                    0.761396          -0.002556  0.027060  0.002461   
OBSERVATION_TIME               NaN                NaN       NaN       NaN   
PIXELS                    0.148481          -0.001046 -0.005644  0.139494   
PRESSURE                  1.000000          -0.000909  0.112234  0.006812   
QUALITY_INDICATOR        -0.000909           1.000000 -0.065000  0.133272   
SAT_ZEN                   0.112234          -0.065000  1.000000 -0.331894   
SCANS                     0.006812           0.133272 -0.331894  1.000000   
UCOMP                    -0.067105           0.079524  0.485157 -0.097119   
VCOMP                     0.146578           0.012702 -0.067521  0.002574   
WIND_DIRECTION            0.006254           0.040614  0.453806 -0.042809   
WIND_SPEED               -0.284217           0.207432  0.229739  0.076226   
obs                       0.005020           0.130881 -0.300650  0.998100 